spring.application.name=Mapping

# PostgreSQL Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# PostgreSQL Database Username and Password
spring.datasource.username=postgres
spring.datasource.password=postgres

# PostgreSQL Driver Class Name
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL auto (e.g., update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update

# Dialect to use for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable SQL logging (optional)
spring.jpa.show-sql=true

# Format SQL logging (optional)
spring.jpa.properties.hibernate.format_sql=true

#For Creating schema
spring.datasource.hikari.schema= mapping

server.port=8081